export default [
  "ahegao",
  "mutual masturbation",
  "voyeurism",
  "sadism",
  "masochism",
  "tentacles",
  "hyung kink",
  "ruined orgasm",
  "married sex",
  "handcuffs",
  "medical play",
  "cop/criminal roleplay",
  "a/b/o",
  "bratty",
  "biting",
  "hair pulling",
  "first time",
  "blindfolds",
  "teacher/student roleplay",
  "boss/secretary roleplay",
  "sex toys",
  "dry humping",
  "teasing",
  "puppy play",
  "objectification",
  "spitting",
  "almost getting caught",
  "rimming",
  "spanking",
  "dirty talk",
  "public sex",
  "makeup sex",
  "shower sex",
  "hatesex",
  "morning sex",
  "phone sex",
  "sensation play",
  "comeplay",
  "casual sex",
  "loud sex",
  "sensory deprivation",
  "foodplay",
  "comfort sex",
  "outdoor sex",
  "prostitution",
  "omorashi",
  "sex machine",
  "drunk sex",
  "humiliation",
  "praise kink",
  "service top/power bottom",
  "rough sex",
  "somnophilia",
  "hickeys",
  "sex marathon",
  "mile high club",
  "birthday sex",
  "silly giggly sex",
  "vampire kink",
  "werewolf kink",
  "alpha/alpha",
  "omega/omega",
  "sex pollen",
  "lingerie",
  "corruption",
  "safeword use",
  "strength kink",
  "felching",
  "chastity belt",
  "nipple play",
  "piercing kink",
  "slave training",
  "sounding",
  "pegging",
  "wax play",
  "prostate massage",
  "watersports",
  "breeding kink",
  "barebacking",
  "blowjobs",
  "hybrids",
  "camboy",
  "69ing",
  "high heels",
  "cock rings",
  "body worship",
  "overstimulation",
  "high sex",
  "breathplay",
  "shibari",
  "begging",
  "collars",
  "aphrodisiacs",
  "size kink",
  "temperature play",
  "crying",
  "sexting",
  "massage",
  "'it's just stress relief'",
  "bukkake",
  "name-calling",
  "groping"
]
