export default [
  "starry night",
  "crying while hugging",
  "sneakers",
  "love at first sight",
  "idiots to lovers",
  "enemies to lovers",
  "friends to lovers",
  "strangers to lovers",
  "slow burn",
  "'shut up and kiss me'",
  "fishnets",
  "underground",
  "forbidden",
  "flowers",
  "artists",
  "kitten",
  "'mario kart is serious business!'",
  "fresh snow",
  "not today",
  "'is that my shirt?'",
  "spring day",
  "'but you hate pancakes'",
  "mutual pining",
  "jealousy",
  "fruit",
  "humiliate",
  "butterfly",
  "doll",
  "strawberry",
  "lavish",
  "prickly",
  "regret",
  "family",
  "triumph",
  "loyalty",
  "domestic",
  "fluff",
  "angst",
  "runaway",
  "'wait, what did you just say?'",
  "confessing during an argument",
  "reunion",
  "summer",
  "sunset",
  "detention",
  "interstellar",
  "backstage",
  "suburbia",
  "'it's not what it looks like'",
  "workaholic",
  "jazzercise",
  "pilates",
  "weightlifting",
  "library",
  "beach",
  "thighs",
  "tteokbokki",
  "'hyung will treat you'",
  "icecream",
  "'make me'",
  "'i'm too sober for this'",
  "'you can't kick me out! this is my bed too!'",
  "'good thing i didn't ask for your opinion'",
  "'did you just hiss at me?'",
  "'wait a minute, are you jealous?'",
  "'this is the stupidest plan you've ever come up with. of course i'm in'",
  "'you did all of this for me?'",
  "fake dating",
  "oh my god they were roommates",
  "'never too late'",
  "'but listen-'",
  "amnesia",
  "touch starved",
  "oblivious",
  "sunrise",
  "shirtless",
  "dimples",
  "'you did that on purpose!'",
  "clothes sharing",
  "sickfic",
  "dancing",
  "dinner",
  "eye contact",
  "dreams",
  "eavesdropping",
  "smoke",
  "sugar",
  "fear",
  "holding hands",
  "'no, it was an accident, i swear-'",
  "sports",
  "caught red-handed",
  "lesson",
  "sauna",
  "immortality",
  "mistake",
  "surprise",
  "bickering",
  "hair",
  "ring",
  "sensitive",
  "5+1",
  "emergency",
  "'can i borrow this?'",
  "tomorrow",
  "fwb but then FEELINGS",
  "suspicious",
  "award",
  "survival",
  "loser",
  "muse",
  "thrift shopping",
  "impulsive",
  "tender",
  "road trip",
  "proposal",
  "snowed in",
  "playful",
  "shatter",
  "overwhelmed",
  "betrayal",
  "lush",
  "dreamscape",
  "determination",
  "escape",
  "ambiguous",
  "wish",
  "rumours",
  "confrontation",
  "nuance",
  "defeat",
  "honesty",
  "empty",
  "stolen",
  "arms",
  "'why are you looking at me like that?'",
  "'what, pray tell, the fuck'"
]
